### ISSUE TITLE
Is this a phishing scam?

### ISSUE THREAD

**Issue by LinuxRocks2000** [joshuahouston/joshuahouston.github.io#1]
Just a thought - Jfact0ry.com looks a lot like jfactory.com, which I have found does not have a website. Is this page originally designed to phishing-scam them? I visited your site and it has a virus that says stuff like "Make money fast for FREE"....

Sorry for any inconvenience or annoyance

**Comment by joshuahouston** [comment]
I did not renew the domain so it belongs to someone else now. I need to remove "jfact0ry.com" from my code and any mention of it. Thanks for the heads up.

**Comment by joshuahouston** [comment]
I think I removed all mentions of jfact0ry.com

**Comment by joshuahouston** [comment]
Actually no I didn't. oops

**Comment by joshuahouston** [comment]
Should be good now
